### ISSUE TITLE
Unable to CREATE INDEX for Encrypted Columns

### ISSUE THREAD

**Issue by saklanipankaj** [aprismatic/prismadb#11]
`CREATE INDEX idx1 ON t1 (a, b);`

> ERROR:  42703: column "a" does not exist

Unable to CREATE INDEX generates an error message that claims that column a does not exists.
SCHEMA:
 Field | Type | Null | Key | Default | Extra |           Encryption
-------+------+------+-----+---------+-------+---------------------------------
 a     | int4 | YES  |     |         |       | Addition, Multiplication, Range
 b     | int8 | YES  |     |         |       | Addition, Multiplication, Range
(2 rows)

**Comment by cheziyi** [comment]
Are you sure you are on the latest version (MySQL 0.3.3.74 / SQL Server 0.3.3.101 / PostgreSQL 0.3.3.36)? We are unable to repro this issue.

**Comment by saklanipankaj** [comment]
Updating the version helped resolve this issue

**Comment by cheziyi** [comment]
This issue is now considered resolved.
