### ISSUE TITLE
Unable to make Encrypted Column an PRIMARY KEY

### ISSUE THREAD

**Issue by saklanipankaj** [aprismatic/prismadb#14]
```
CREATE TABLE t3
(
    a INT ENCRYPTED FOR(MULTIPLICATION, ADDITION, SEARCH, STORE, RANGE) NOT NULL PRIMARY KEY,
    b DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    c ENUM('abc','bcd','cde','def') ENCRYPTED FOR(SEARCH, STORE) NOT NULL,
    d BLOB ENCRYPTED FOR(SEARCH, STORE) NULL,
    e TEXT ENCRYPTED FOR(SEARCH, STORE) NULL,
    f CHAR ENCRYPTED FOR(SEARCH, STORE) NULL,
    g VARCHAR(100)
);

INSERT INTO t3 (a, c, e, f) VALUES
( 1, 'abc', 'Hello', 'd'),
(12, 'bcd', 'Test', 'z'),
( 0, 'abc', 'This is encrypted', 'd'),
(71, 'cde', 'Last', 'a'),
( 1, 'abc', 'Hello', 'd'),
(12, 'bcd', 'Test', 'z'),
( 0, 'abc', 'This is encrypted', 'd'),
(71, 'cde', 'Last', 'a');

SHOW KEYS FROM t3;
```

> 
> Query OK, 0 rows affected (0.01 sec)
> Query OK, 4 rows affected (0.05 sec)
> Query OK, 4 rows affected (0.05 sec)
> 
> +-------+------------+----------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
> | Table | Non_unique | Key_name | Seq_in_index | Column_name    | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
> +-------+------------+----------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
> | t3    |          0 | PRIMARY  |            1 | prismadb_rowid | A         |          16 |     NULL | NULL   |      | BTREE      |         |               |
> +-------+------------+----------+--------------+----------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
> 1 row in set (0.00 sec)

A table can be created where an encrypted table is specified as the PRIMARY KEY however, it is not created as such, allowing same values being used in the PRIMARY KEY column. The default PRIMARY KEY is created and used for the table instead by the MySQL database.

**Comment by cheziyi** [comment]
Primary keys can not be encrypted by Prisma/DB, and also should not be encrypted, as it removes the unique and indexing properties of a primary key column. Primary keys are recommended to be unencrypted auto-incrementing IDs, or tokenized PIDs. This issue will remain open, as an error needs to be thrown if a user tries to create a column as such.
