### ISSUE TITLE
Ambiguous Error when using (') im MYSQL Query

### ISSUE THREAD

**Issue by saklanipankaj** [aprismatic/prismadb#15]
```
SELECT (a+b), (a*b) AS ‘MU’, (b-a)
FROM t1;
```

> ERROR 13180 (HY000): Unknown column 'a' in 'field list'
Ambiguous Error statement, unable to process column name in (‘), when wiki examples showcases the use of (').

**Comment by cheziyi** [comment]
Same issue as https://github.com/PrismaDB/PrismaDB/issues/16#issuecomment-506364847.
