### ISSUE TITLE
Undesired Result when using (') around column name in Select Statement MySQL

### ISSUE THREAD

**Issue by saklanipankaj** [aprismatic/prismadb#16]
```
SELECT ‘a’, ‘b’
FROM t1;

```

> +------+------+
> | 'a'  | 'b'  |
> +------+------+
> | a    | b    |
> | a    | b    |
> | a    | b    |
> | a    | b    |
> | a    | b    |
> | a    | b    |
> | a    | b    |
> | a    | b    |
> | a    | b    |
> | a    | b    |
> | a    | b    |
> | a    | b    |
> +------+------+
> 12 rows in set (0.00 sec)

Wiki example uses quotes(‘) for query. Query with Quotes for column returns an invalid result.

**Comment by cheziyi** [comment]
The examples in the wiki portrays the use of backticks `` ` ``, and not single quotes `'`. In MySQL, backticks are used for object names, and single quotes are used for strings. This issue is thus considered closed.
