### ISSUE TITLE
Unable to SELECT from table created using backticks(`) in MySQL

### ISSUE THREAD

**Issue by saklanipankaj** [aprismatic/prismadb#21]
```
CREATE TABLE `farm` (
  `animal_id` int(11) NOT NULL AUTO_INCREMENT,
  `animal_type` int(11) NOT NULL,
  `animal_description` varchar(255) NOT NULL,
  `animal_name` varchar(255) NOT NULL,
  PRIMARY KEY (`animal_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

INSERT INTO `farm` VALUES(1, 2, 'spotted', 'Mal');
INSERT INTO `farm` VALUES(2, 4, 'spotted', 'Zoe');
INSERT INTO `farm` VALUES(3, 1, 'solid color', 'Wash');
INSERT INTO `farm` VALUES(4, 2, 'solid color', 'Inara');

SELECT * FROM `farm`;
```
> 
> Query OK, 0 rows affected (0.03 sec)
> Query OK, 1 row affected (0.00 sec)Query OK, 1 row affected (0.00 sec)Query OK, 1 row affected (0.00 sec)Query OK, 1 row affected (0.00 sec)
> ERROR 13180 (HY000): Table `farm` does not exist.

Able to create and insert into table created using backticks, however unable to run SELECT statement for the table.

**Comment by cheziyi** [comment]
This is actually an issue with an unsupported `CREATE TABLE` statement. As the `CREATE TABLE` contains some elements which is not parsed by Prisma/DB, the statement is executed at the actual database directly without going through the transformative core. Therefore, the Prisma/DB core is not aware of the table being created, and thus unable to retrieve information about the table while performing a `SELECT` query.

However, in this case, `INSERT` queries should not have executed successfully too, and an error should be thrown to inform users that the table does not exist when inserting.
