### ISSUE TITLE
Incorrect Location in Error Message When Creating Table in MSSQL

### ISSUE THREAD

**Issue by saklanipankaj** [aprismatic/prismadb#22]
```
CREATE TABLE t2(    
a FLOAT ENCRYPTED FOR (MULTIPLICATION, ADDITION, RANGE) PRIMARY KEY,    
b INT ENCRYPTED FOR (MULTIPLICATION, ADDITION, RANGE) PRIMARY KEY,    
c VARCHAR(100),    
d TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
); 
```
> HResult 0x4E21, Level 16, State 1Incorrect syntax near the keyword 'FOR'. 

Incorrect place cited for the error as the error is CURRENT_TIMESTAMP which is located near the DEFAULT keyword.

**Comment by cheziyi** [comment]
Same as https://github.com/PrismaDB/PrismaDB/issues/5, closed to remove duplicate issues.
