### ISSUE TITLE
Unreadble Formatting of Results in MSSQL

### ISSUE THREAD

**Issue by saklanipankaj** [aprismatic/prismadb#23]
`SHOW COLUMNS FROM t1;
`
<img width="960" alt="SNAP1" src="https://user-images.githubusercontent.com/31514745/60280214-110ea680-9935-11e9-9929-32f3948e43bc.PNG">
<img width="960" alt="SNAP2" src="https://user-images.githubusercontent.com/31514745/60280215-110ea680-9935-11e9-82a3-010694ca1496.PNG">

The results returned for several results Queries is formatted poorly, resulting in the RESULT being displayed across several pages, making it almost unreadable for the user.

**Comment by cheziyi** [comment]
This is more of an issue with the sqlcmd client, it displays columns with the width of the columns's maximum length. Connecting to a normal SQL Server database yields the same display.
