### ISSUE TITLE
Able to Create New Database

### ISSUE THREAD

**Issue by saklanipankaj** [aprismatic/prismadb#8]
`CREATE DATABASE "TEST";`

New Database can be created and connected to using the demo docker container. User should not be allowed to do so.

**Comment by cheziyi** [comment]
`CREATE DATABASE` statements are not parsed and handled by the Core, and are forwarded to the database directly. We do not explicitly prevent users from doing so. Users will not be able to connect to the new database, as the database that the proxy connects to is fixed, so there will not be any issues.

This is therefore not an issue, and is closed.
